### ISSUE TITLE
SampleSource Should Utilize Conformance Tests

### ISSUE THREAD

**Issue by lberk** [knative-sandbox/sample-source#73]
As eventing builds up source conformance tests, we should make sure we run them during PRs on sample-source

/cc @aliok

**Comment by matzew** [comment]
@Abd4llA this might be something for you :-)

**Comment by aliok** [comment]
I think this is still valid and it is a nice to have for source writers.

However, doing this was not possible because the source conformance tests pretty much don't exist at the moment and it ignited a testing task force to some problems that were revealed.

Let's keep this open.

/remove-lifecycle stale
